# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-12 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=3)),
                ('last_time_donated', models.DateField()),
                ('name', models.CharField(max_length=60)),
                ('contact', models.IntegerField(max_length=10)),
                ('address', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
    ]
