# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-12 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
