# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-14 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donation', '0006_auto_20170414_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contact',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
